/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FloatContainer: typeof import('./components/FloatContainer.vue')['default']
    InputWithType: typeof import('./components/InputWithType.vue')['default']
    Switch: typeof import('./components/Switch.vue')['default']
  }
}
